<?php
namespace Abdurrazaq\Inspire;
use Illuminate\Support\Collection;

class Inspiring
{
	
	public static function quote() {
		return Collection::make([
            "If someone is better than you at something, it just means the person has FAILED more at that thing than you have. - Christian Nwamba",
            "Talk is cheap. Show me the code. - Linus Torvalds",
            "Programs must be written for people to read, and only incidentally for machines to execute. -Harold Abelson,",
            "Truth can only be found in one place: the code.- Robert C. Martin",
            "Walking on water and developing software from a specification are easy if both are frozen.-Edward V. Berard",
            "Gbogbo alangba lo d'anu dele, a ko mo eyi t'inu nrun - Yoruba People of Nigeria",
            "Ile la ti n ko eso re ode - Yoruba People of Nigeria",
            "A pę ko to jęun, ki ję ibaję - Yoruba People of Nigeria",
            "Eewu bę loko Longę, Longę fun ara rę eewu ni - Yoruba People of Nigeria",
            "Kò sí ęni tí ó ma gùn ęşin tí kò ní ju ìpàkó. Bí kò fę ju ìpàkó, ęşin tí ó ngùn á ję kojū. - Yoruba People of Nigeria",
            "Bí abá so òkò sójà ará ilé eni ní bá; - Yoruba People of Nigeria",
            "Díẹ̀ díẹ̀ nimú ẹlẹ́dẹ̀ẹ́ fi ń wọgbà - Yoruba People of Nigeria",
            "Ilé ọba tójó ẹwà ló bùsi - Yoruba People of Nigeria",
            "Gidi gidi bụ ugwu eze.(Unity is strength) - Igbo People Of Nigeria",
            "Chọọ ewu ojii ka chi dị.(Make hay while the sun shines) - Igbo People Of Nigeria",
            "Otu onye tuo izu, o gbue ochu.(Knowledge is never complete: two heads are better than one.) - Igbo People Of Nigeria",
            "Ihe ehi hụrụ gbalaba oso ka okuku huru na-atụ onu - Igbo People Of Nigeria",
            "Where one falls is where his god pushed him down. - Igbo People Of Nigeria",
            "Time and tide wait for nobody. - Igbo People Of Nigeria",
            "What was secret is revealed in the market place. - Igbo People Of Nigeria",
            "Who knows how water entered into the stalk of the pumpkin? - Igbo People Of Nigeria",
            "A goat that dies in a barn was never killed by hunger. - Igbo People Of Nigeria",
            "Salute the deaf; if the heavens don't hear, the earth will hear. - Igbo People Of Nigeria",
            "An indigent does not take the title of \"Omeokachie\" (i.e. one who completes whatever he puts his hand to) - Igbo People Of Nigeria",
            "Those who defecate at night see the ghost grasshopper. - Igbo People Of Nigeria",
            "If a child lifts his father, his scrotum will blindfold him. - Igbo People Of Nigeria",
            "If one fails to lick his lips, the harmattan will do it. - Igbo People Of Nigeria",
            "Okuko mmanya na-egbu ahubeghi mmanwulu ara na-ayi.(A drunken fowl has not met a mad fox.) - Igbo People Of Nigeria",
            "Onye si na ya anaghi ata anu nkita, ya arakwala mmiri ofe ya.(He who abhors dog meat should not eat dog-meat soup.) - Igbo People Of Nigeria",
            "A tuoro omara, o mara, a tuoro ofeke,o fenye ishi n'ohia (If you tell a wise one, he understands; tell a dunce, he runs into the bush.) - Igbo People Of Nigeria ",
            "Wisdom is wealth. ~ Swahili",
            "Wisdom is like a baobab tree; no one individual can embrace it. ~ Akan proverb",
            "The fool speaks, the wise man listens. ~ Ethiopian proverb",
            "Wisdom does not come overnight. ~ Somali proverb",
            "The heart of the wise man lies quiet like limpid water. ~ Cameroon proverb",
            "Wisdom is like fire. People take it from others. ~ Hema (DRC) proverb",
            "Only a wise person can solve a difficult problem. ~ Akan proverb",
            "Knowledge without wisdom is like water in the sand. ~ Guinean proverb",
            "In the moment of crisis, the wise build bridges and the foolish build dams. ~ Nigerian proverb",
            "If you are filled with pride, then you will have no room for wisdom. ~ African proverb",
            "A wise person will always find a way. ~ Tanzanian proverb",
            "Nobody is born wise. ~ African proverb",
            "A man who uses force is afraid of reasoning. ~Kenyan proverb",
            "Wisdom is not like money to be tied up and hidden. ~ Akan proverb",
            "It takes a village to raise a child. ~ African proverb",
            "Many hands make light work. ~ Haya (Tanzania) proverb",
            "Where there are many, nothing goes wrong. ~ Swahili proverb",
            "Two ants do not fail to pull one grasshopper. ~ Tanzanian proverb",
            "A single bracelet does not jingle. ~ Congolese proverb",
            "A single stick may smoke, but it will not burn. ~ African proverb",
            "If you want to go quickly, go alone. If you want to go far, go together. ~ African proverb",
            "A family is like a forest, when you are outside it is dense, when you are inside you see that each tree has its place. ~ African Proverb",
            "A united family eats from the same plate. ~ Baganda proverb",
            "A family tie is like a tree, it can bend but it cannot break. ~ African proverb",
            "The wealth which enslaves the owner isn’t wealth. ~ Yoruba",
            "The rich are always complaining. ~ Zulu",
            "Lack of money is lack of friends; if you have money at your disposal, every dog and goat will claim to be related to you. ~ Yoruba",
            "With wealth one wins a woman. ~ Uganda",
            "What you give you get, ten times over. ~ Yoruba",
            "Don’t make a goat your friend if your skirt is made of leaves. – Nigeria",
            "No person is wise at all times. – Somalia",
            "A person’s life is dependent on a listening ear. – Zambia",
            "If you don’t know where you’re going, any road will take you there. – Uganda",
            "A good name is better than a good perfume. – Ethiopia",
            "It is better to be a lion for a day than to be a sheep all your life. – Ghana",
            "A man doesn’t go far from where his corn is roasting. – Nigeria",
            "Oruko rere o da ju wura ati fadaka lo (A good name is better than gold and silver) - Yoruba people of Nigeria ",
		    "Epe ibinu ko pa odi (Cursing a deaf in anger has no effect) - Yoruba people of Nigeria",
		    "A yi, a gamma, ta fi takamma, gobe a koma.(To do, to finish, is better than don't care, come back to-morrow.) - Hausa people of Nigeria",
		    "What an elder saw while sitting, a youth could not see it.",
		    "Coffee and love taste best when hot. ~ Ethiopian Proverb",
		    "Time destroys all things. ~ Nigerian Proverb",
		    "Little by little the bird builds its nest. ~ Nigerian Proverb",
		    "Numbers can achieve anything. ~ Ghanaian Proverb",
		    "A brave man dies once, a coward a thousand times. ~ Somali Proverb",
		    "Only someone else can scratch your back. ~ Kenyan Proverb",
		    "It’s like removing a hyena from a pit. ~ Meru Proverb",
		    "Misfortune of soup made of shanks and feet. ~ Xhosa Proverb",
		    "He who does not seize opportunity today, will be unable to seize tomorrow’s opportunity. ~ Somali Proverb",
		    "Rich people sometimes eat bad food. ~ Kikuyu Proverb",
		    "He who refuses to obey cannot command. ~ Kenyan Proverb",
		    "The cow that bellows does so for all cows. ~ Kenyan Proverb",
		    "If an arrow has not entered deeply, then its removal is not hard. ~ Buli Proverb",
		    "The chameleon changes color to match the earth, the earth doesn’t change colors to match the chameleon. ~ Senegalese Proverb",
		    "If an arrow has not entered deeply, then its removal is not hard. ~ Buli Proverb",
		    "Where error gets to, correction cannot reach. ~ Ghanaian Proverb",
		    "You cannot climb to the mountain top without crushing some weeds with your feet ~ Ugandan Proverb",
		    "Even the best dancer on the stage must retire sometime. ~ African Proverb",
		    "Do not call to a dog with a whip in your hand. ~ Sudanese Proverb",
		    "It is the belly which daily gives thanks. ~ Maasai Proverb",
		    "Too much discussion leads to a quarrel. ~ Ivorian Proverb",
		    "He who tells the truth is never wrong. ~ Swahili Proverb ",
		    "One head alone does not go into council ~ Ghanaian Proverb",
		    "The rain does not recognize anyone as a friend it drenches all equally. ~ Ibo Proverb (Nigeria)",
            "Being happy is better than being king. ~ Nigerian Proverb",
            "The roaring lion kills no prey ~ Nigerian Proverb",
            "If the wind blows, it enters every crevice. ~ Egyptian Proverb",
            "The more feathers a chicken has, the bigger it looks. ~ Zambian Proverb",
            "If two wise men always agree, then there is no need for one of them. ~ Zambian Proverb",
            "A child’s lie is like a dead fish in a pond that in the end, always comes to the surface, explains his mother. ~Luo proverb",
            "Those who accomplish great things pay attention to little ones. ~Malian Proverb",
            "Slowly, slowly, porridge goes into the gourd. ~ Kuria People of Kenyan & Tanzania",
            "You cannot force water up a hill. ~ Maasai Proverb ",
            "Even the Niger river must flow around an island. ~ Hausa Proverb",
            "Where you will sit when you are old shows where you stood in youth. ~ Yoruba Proverb",
        ])->random();
	}
}
 return "HEY";